export const SEND_REGISTRATION_ERROR = "registration/SEND_REGISTRATION_ERROR";
export const SEND_REGISTRATION_FETCH = "registration/SEND_REGISTRATION_FETCH";
export const SEND_REGISTRATION_DATA = "registration/SEND_REGISTRATION_DATA";
