---
version: 2
plan:
  project-key: WEN
  key: FRONTENDEXCHANGEPROD
  name: Webnet Exchange Frontend 
stages:
  - Default Stage:
      manual: false
      final: false
      jobs:
        - Default Job
Default Job:
  key: JOB1
  tasks:
    - checkout:
        force-clean-build: 'false'
        description: Checkout Default Repository
    - script:
        interpreter: SHELL
        scripts:
          - echo PLAN_NAME="$( echo '${bamboo.planKey}' | tr '[:upper:]' '[:lower:]')" > variables
        description: Set ENV Variable
    - inject-variables:
        file: variables
        scope: RESULT
        namespace: inject
        description: Inject Variable
    - any-task:
        plugin-key: com.atlassian.bamboo.plugins.bamboo-docker-plugin:task.docker.cli
        configuration:
          commandOption: build
          repository: docker.atican.dev/${bamboo.inject.PLAN_NAME}:${bamboo.buildNumber}
          dockerfileOption: existing
          nocache: 'false'
          save: 'false'
        description: Build Image
    - any-task:
        plugin-key: com.atlassian.bamboo.plugins.bamboo-docker-plugin:task.docker.cli
        configuration:
          commandOption: push
          pushRepository: docker.atican.dev/${bamboo.inject.PLAN_NAME}:${bamboo.buildNumber}
          registryOption: custom
        description: Push Image
  artifact-subscriptions: []
branches:
  create: manually
  delete:
    after-deleted-days: 1
    after-inactive-days: never
  link-to-jira: true
notifications:
  - events:
      - plan-responsibility-changed
    recipients:
      - responsible
  - events:
      - job-error
    recipients:
      - responsible
      - committers
      - watchers
  - events:
      - plan-completed
    recipients:
      - committers
      - watchers
labels: []
dependencies:
  require-all-stages-passing: false
  enabled-for-branches: true
  block-strategy: none
  plans: []
other:
  concurrent-build-plugin: system-default
  all-other-apps:
    custom:
      buildNumber.enableSyncBranchBuildNumber: 'true'
      buildExpiryConfig.enabled: 'false'
      queue.priority: DEFAULT
---
version: 2
plan:
  key: WEN-FRONTENDEXCHANGEPROD
plan-permissions:
  - users:
      - nick
    permissions:
      - view
      - edit
      - build
      - clone
      - admin
  - groups:
      - TFW DevOps
      - the-fast-way-pm
    permissions:
      - view
      - edit
      - build
      - clone
      - admin
  - groups:
      - TFW Frontend Devs
    permissions:
      - view
      - edit
      - build
      - clone
---
version: 2
deployment:
  name: Webnet Exchange Frontend Deployment
  source-plan: WEN-FRONTENDEXCHANGEPROD
release-naming:
  next-version-name: release-192
  applies-to-branches: false
  auto-increment: true
  auto-increment-variables: []
environments:
- Production Server
Production Server:
  triggers:
  - build-success
  tasks:
    - clean
    - script:
        interpreter: SHELL
        scripts:
          - echo PLAN_NAME="$( echo '${bamboo.planKey}' | tr '[:upper:]' '[:lower:]')" > variables
    - inject-variables:
        file: variables
        scope: LOCAL
        namespace: inject
    - ssh:
        host: 52.31.85.60
        command: 'source ~/.profile && source ~/.bash_profile && cd /home/ubuntu/opendax && sed -i "s/frontend: docker.atican.dev\/${bamboo.inject.PLAN_NAME}:[a-zA-Z0-9!@#|,.<>\/?\-]*/frontend: docker.atican.dev\/${bamboo.inject.PLAN_NAME}:${bamboo.buildNumber}/g" config/app.yml  && rake render:config && docker-compose up -d frontend'
        authentication:
          username: ubuntu
          shared-credentials: ID_AWS
  final-tasks: []
  variables: {}
  requirements: []
  notifications: []
---
version: 2
deployment:
  name: Webnet Exchange Frontend Deployment
deployment-permissions:
  - users:
      - nick
    permissions:
      - view
      - edit
environment-permissions:
- Production Server:
  - users:
    - nick
    permissions:
    - view
    - edit
    - deploy
  - groups:
    - TFW DevOps
    - the-fast-way-pm
    - TFW Frontend Devs
    permissions:
    - view
    - edit
    - deploy
